// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: packages/grpcapi/server.proto

package grpcapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceCollectorServer_SendMetric_FullMethodName = "/grpcapi.ServiceCollectorServer/SendMetric"
)

// ServiceCollectorServerClient is the client API for ServiceCollectorServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceCollectorServerClient interface {
	//
	SendMetric(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricRequest, MetricResponse], error)
}

type serviceCollectorServerClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceCollectorServerClient(cc grpc.ClientConnInterface) ServiceCollectorServerClient {
	return &serviceCollectorServerClient{cc}
}

func (c *serviceCollectorServerClient) SendMetric(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricRequest, MetricResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ServiceCollectorServer_ServiceDesc.Streams[0], ServiceCollectorServer_SendMetric_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MetricRequest, MetricResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServiceCollectorServer_SendMetricClient = grpc.ClientStreamingClient[MetricRequest, MetricResponse]

// ServiceCollectorServerServer is the server API for ServiceCollectorServer service.
// All implementations must embed UnimplementedServiceCollectorServerServer
// for forward compatibility.
type ServiceCollectorServerServer interface {
	//
	SendMetric(grpc.ClientStreamingServer[MetricRequest, MetricResponse]) error
	mustEmbedUnimplementedServiceCollectorServerServer()
}

// UnimplementedServiceCollectorServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceCollectorServerServer struct{}

func (UnimplementedServiceCollectorServerServer) SendMetric(grpc.ClientStreamingServer[MetricRequest, MetricResponse]) error {
	return status.Error(codes.Unimplemented, "method SendMetric not implemented")
}
func (UnimplementedServiceCollectorServerServer) mustEmbedUnimplementedServiceCollectorServerServer() {
}
func (UnimplementedServiceCollectorServerServer) testEmbeddedByValue() {}

// UnsafeServiceCollectorServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceCollectorServerServer will
// result in compilation errors.
type UnsafeServiceCollectorServerServer interface {
	mustEmbedUnimplementedServiceCollectorServerServer()
}

func RegisterServiceCollectorServerServer(s grpc.ServiceRegistrar, srv ServiceCollectorServerServer) {
	// If the following call panics, it indicates UnimplementedServiceCollectorServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceCollectorServer_ServiceDesc, srv)
}

func _ServiceCollectorServer_SendMetric_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServiceCollectorServerServer).SendMetric(&grpc.GenericServerStream[MetricRequest, MetricResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ServiceCollectorServer_SendMetricServer = grpc.ClientStreamingServer[MetricRequest, MetricResponse]

// ServiceCollectorServer_ServiceDesc is the grpc.ServiceDesc for ServiceCollectorServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceCollectorServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.ServiceCollectorServer",
	HandlerType: (*ServiceCollectorServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMetric",
			Handler:       _ServiceCollectorServer_SendMetric_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "packages/grpcapi/server.proto",
}
