// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: packages/grpcapi/server.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Metric        string                 `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	Value         float32                `protobuf:"fixed32,3,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricRequest) Reset() {
	*x = MetricRequest{}
	mi := &file_packages_grpcapi_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRequest) ProtoMessage() {}

func (x *MetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_grpcapi_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRequest.ProtoReflect.Descriptor instead.
func (*MetricRequest) Descriptor() ([]byte, []int) {
	return file_packages_grpcapi_server_proto_rawDescGZIP(), []int{0}
}

func (x *MetricRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *MetricRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *MetricRequest) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type MetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricResponse) Reset() {
	*x = MetricResponse{}
	mi := &file_packages_grpcapi_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricResponse) ProtoMessage() {}

func (x *MetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_grpcapi_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricResponse.ProtoReflect.Descriptor instead.
func (*MetricResponse) Descriptor() ([]byte, []int) {
	return file_packages_grpcapi_server_proto_rawDescGZIP(), []int{1}
}

func (x *MetricResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_packages_grpcapi_server_proto protoreflect.FileDescriptor

const file_packages_grpcapi_server_proto_rawDesc = "" +
	"\n" +
	"\x1dpackages/grpcapi/server.proto\x12\agrpcapi\x1a\x1fgoogle/protobuf/timestamp.proto\"u\n" +
	"\rMetricRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x02R\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"4\n" +
	"\x0eMetricResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged2Y\n" +
	"\x16ServiceCollectorServer\x12?\n" +
	"\n" +
	"SendMetric\x12\x16.grpcapi.MetricRequest\x1a\x17.grpcapi.MetricResponse(\x01B$Z\"github.com/Krunis/packages/grpcapib\x06proto3"

var (
	file_packages_grpcapi_server_proto_rawDescOnce sync.Once
	file_packages_grpcapi_server_proto_rawDescData []byte
)

func file_packages_grpcapi_server_proto_rawDescGZIP() []byte {
	file_packages_grpcapi_server_proto_rawDescOnce.Do(func() {
		file_packages_grpcapi_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_grpcapi_server_proto_rawDesc), len(file_packages_grpcapi_server_proto_rawDesc)))
	})
	return file_packages_grpcapi_server_proto_rawDescData
}

var file_packages_grpcapi_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_packages_grpcapi_server_proto_goTypes = []any{
	(*MetricRequest)(nil),  // 0: grpcapi.MetricRequest
	(*MetricResponse)(nil), // 1: grpcapi.MetricResponse
}
var file_packages_grpcapi_server_proto_depIdxs = []int32{
	0, // 0: grpcapi.ServiceCollectorServer.SendMetric:input_type -> grpcapi.MetricRequest
	1, // 1: grpcapi.ServiceCollectorServer.SendMetric:output_type -> grpcapi.MetricResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packages_grpcapi_server_proto_init() }
func file_packages_grpcapi_server_proto_init() {
	if File_packages_grpcapi_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_grpcapi_server_proto_rawDesc), len(file_packages_grpcapi_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_packages_grpcapi_server_proto_goTypes,
		DependencyIndexes: file_packages_grpcapi_server_proto_depIdxs,
		MessageInfos:      file_packages_grpcapi_server_proto_msgTypes,
	}.Build()
	File_packages_grpcapi_server_proto = out.File
	file_packages_grpcapi_server_proto_goTypes = nil
	file_packages_grpcapi_server_proto_depIdxs = nil
}
